export const RSVP_FETCH = "RSVP_FETCH";
export const RSVP_CREATE = "RSVP_CREATE";
export const RSVP_DELETE = "RSVP_DELETE";
export const RSVP_GET_FIRST = "RSVP_GET_FIRST";
export const RSVP_GET_SECOND = "RSVP_GET_SECOND";
export const RSVP_GET_THRID = "RSVP_GET_THRID";
export const RSVP_UPDATE = "RSVP_UPDATE";
export const RSVP_CHECKING_PHOTOANDPEOPLE = "RSVP_CHECKING_PHOTOANDPEOPLE";


